# Generated by Django 3.2.9 on 2023-01-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_time', models.DateTimeField()),
                ('Slot_status', models.CharField(choices=[('E', 'Empty'), ('A', 'Added'), ('D', 'Declined')], default='E', max_length=1)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.intervieweraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment', models.CharField(choices=[('S', 'Successful'), ('P', 'Pending'), ('D', 'Declined')], default='P', max_length=1)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('Interviewer_Slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedules')),
                ('Student_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.intervieweeaccount')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.intervieweraccount')),
            ],
        ),
    ]
