# Generated by Django 3.2.9 on 2022-11-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_time', models.DateTimeField()),
                ('Slot_status', models.CharField(choices=[('E', 'Empty'), ('A', 'Added'), ('D', 'Declined')], default='E', max_length=1)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.intervieweraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('D', 'Declined')], default='None', max_length=1)),
                ('Interviewer_Slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedules')),
                ('Student_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.intervieweeaccount')),
            ],
        ),
    ]
