# Generated by Django 3.2.9 on 2023-01-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduled',
            old_name='uid',
            new_name='Interviewer_uid',
        ),
    ]
