# Generated by Django 3.2.9 on 2022-11-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled',
            name='status',
        ),
        migrations.AddField(
            model_name='scheduled',
            name='Payment',
            field=models.CharField(choices=[('S', 'Successful'), ('P', 'Pending'), ('D', 'Declined')], default='P', max_length=1),
        ),
    ]
