# Generated by Django 3.2.9 on 2022-11-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20221128_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='Interviewer_Slot',
            field=models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedules'),
        ),
    ]
