# Generated by Django 3.2.9 on 2023-01-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_rename_uid_scheduled_interviewer_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='Payment',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='P', max_length=20),
        ),
    ]
