# Generated by Django 3.2.9 on 2022-12-27 06:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_interviewer', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntervieweeAccount',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.basicaccount')),
                ('Occupation', models.CharField(blank=True, choices=[('STUDENT', 'STUDENT'), ('JOB', 'JOB')], max_length=60, null=True)),
                ('Company', models.CharField(max_length=60)),
                ('Institute_name', models.CharField(blank=True, max_length=60, null=True)),
                ('State', models.CharField(blank=True, max_length=40, null=True)),
                ('City', models.CharField(blank=True, max_length=40, null=True)),
                ('Year_of_study', models.CharField(blank=True, max_length=60, null=True)),
                ('Residence', models.CharField(blank=True, max_length=60, null=True)),
                ('Res_city', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerAccount',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.basicaccount')),
                ('Age', models.CharField(blank=True, max_length=10, null=True)),
                ('Experience', models.CharField(blank=True, max_length=40, null=True)),
                ('Price', models.CharField(blank=True, max_length=30, null=True)),
                ('About_me', models.CharField(blank=True, max_length=200, null=True)),
                ('Linkedin', models.URLField(blank=True)),
                ('profile_image', models.ImageField(default='dafault.svg', upload_to='pics')),
            ],
        ),
    ]
