# Generated by Django 3.2.9 on 2022-11-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweraccount',
            name='profile_image',
            field=models.ImageField(default='dafault.svg', upload_to='pics'),
        ),
    ]
