# Generated by Django 3.2.9 on 2022-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_basicaccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervieweraccount',
            name='Linkedin',
            field=models.URLField(blank=True),
        ),
    ]
