# Generated by Django 3.2.9 on 2022-11-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221130_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweraccount',
            name='Domain',
            field=models.CharField(blank=True, choices=[('DSA', 'DSA'), ('FULLSTACK', 'FULLSTACK'), ('IELTS', 'IELTS'), ('AI AND DS', 'AI AND DS'), ('CYBER AND NETWORK SECURITY', 'CYBER AND NETWORK SECURITY')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basicaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='intervieweraccount',
            name='Age',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='intervieweraccount',
            name='Experience',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='intervieweraccount',
            name='Price',
            field=models.PositiveSmallIntegerField(default=1520),
        ),
    ]
