# Generated by Django 3.2.9 on 2022-12-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221130_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervieweraccount',
            name='Domain',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
